### ISSUE TITLE
Order of the areas

### ISSUE THREAD

**Issue by antyone** [Fallstreak6/PoE-Region-Searcher#1]
I wish the order of the areas in the overlay would match the one from the game.

If you notice, the order of the areas in-game go from 1-8 (haewark hamlet, tirn's end, lex proxima, lex ejoris, new vastir, glennach cairns, valdo's rest, lira arthain)

You can check that order by mousing-over the area designated for your watchstones thats in your atlas and it follows an order going from top left-top right, down left-down right

It would be nice if the region overlay would follow the same order.

**Comment by antyone** [comment]
The picture hopefully shows what I mean, if you understand how it visually follows an order you wouldn't even need to read the areas in order to know what you are looking for

![123124](https://user-images.githubusercontent.com/17205651/72174282-43638b00-33d1-11ea-900e-f4c0abef67a5.png)

**Comment by antyone** [comment]
This is off topic but I also noticed the overlay resets its position if you close it down and open up again, if possible it would be nice if the overlay remembered its window position.

If you also wanted to make some changes to the design I would suggest trying to make it more transparent so it blends well into the game UI.

**Comment by Fall6** [comment]
@antyone Added in 1.1 :)
